### ISSUE TITLE
Error al visualizar los pensum

### ISSUE THREAD

**Issue by Acalix-unicah** [UNICAH-ICC-SAP/GestionPracticasWeb#28]
Buen día.

Favor validar el siguiente error.

```
Error: WHERE parameter "id_carrera" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abstract

\query-generator.js:1746:13)
    at C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1737:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abstrac

t\query-generator.js:1735:35)
    at MySQLQueryGenerator.getWhereConditions (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abst

ract\query-generator.js:2078:19)
    at MySQLQueryGenerator.selectQuery (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abstract\qu

ery-generator.js:991:28)
    at MySQLQueryInterface.select (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\dialects\abstract\query-i

nterface.js:407:59)
    at carrera_clase_bloque.findAll (C:\DevProy\GestionPracticas\Api\node_modules\sequelize\lib\model.js:1140:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getClassBy (C:\DevProy\GestionPracticas\Api\app\controllers\pensumController.js:31:24)
```

Este error no me permite visualizar la información de los pensums de cada carrera.

![image](https://github.com/user-attachments/assets/2669cacf-5cf0-4a6e-8957-e2dc9514f8f2)
![image](https://github.com/user-attachments/assets/0e204c00-edc4-4d63-b855-9caa219aa1fe)
![image](https://github.com/user-attachments/assets/bcafa8a0-665d-4dcf-a08e-a8c709c0b212)

**Comment by cargon86** [comment]
Validado y solucionado
* UNICAH-ICC-SAP/GestionPracticasApi/issues/15
